name: Execute NBA analyzer.

on:
  schedule:
    - cron: "10 9 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.1' # install the python version needed

      - name: install python packages
        run: pip install selenium

      - name: execute py script # run main.py
        run: |
          python analytics/nba_analyzer.py
          python analytics/nba_performance.py

      - name: Pull latest changes from remote
        run: git pull origin main

      - name: commit files
        run: |
          git config user.name "jonasnatividad"
          git config user.email "jonas.natividad.ii@gmail.com"
          git add .
          git commit -m "Daily NBA analyzer update." || echo "No changes to commit"
          git push origin main